export {
  collapseFootball,
  setCollapseQuickLink,
  collapseQuickLink,
  clearTriggerTournament,
  triggerTournament,
  closeQuickLink,
  setOdd,
  clearTournamentCollapse,
  setTournamentCollapse,
  collapseSportTournament,
  changeTournamentMarketGroup,
  changeTournamentMarketGroup2,
  addMarketGroup,
  saveQuickLinkData,
  saveFeaturedEvents,
  setHorseGroupCollapse,
  collapseHorseGroup,
  saveHorseQuickLinks,
} from 'redux/reducers/football';
